### ISSUE TITLE
tinyint(1) converted to number

### ISSUE THREAD

**Issue by TilmannBaumgarten** [RobinBlomberg/kysely-codegen#81] opened 2023-06-09 13:17 UTC
Working with planetscale/mysql, tinyint(1) columns are converted to the `number` type. Is this intended? How do I generate booleans?

**Comment by igalklebanov** [comment] 2023-07-09 01:57
Hey 👋 

MySQL doesn't have a boolean data type. You typically define boolean columns with the `tinyint(1)` data type and use `1` for `true` and `0` for `false`. `tinyint(1)` can also be used to store small numbers as it accepts numbers between [-128, 127].

kysely-codegen cannot tell if you're using that `tinyint(1)` column as a boolean, or as a small number column.

Perhaps a good approach would be to allow users to override with the `SqlBool` type that Kysely exports, or provide a flag that does it automatically.

**Comment by RobinBlomberg** [comment] 2023-08-08 07:59
From what I can gather, this is a duplicate of #30.

**Closed by RobinBlomberg** 2023-08-08 07:59 UTC
