### ISSUE TITLE
kysely-codegen shouldn't crash if `.env` file doesn't exist

### ISSUE THREAD

**Issue by SimonSimCity** [RobinBlomberg/kysely-codegen#214] opened 2024-10-25 14:34 UTC
The command `kysely-codegen` is crashing in my environment (at least when adding a flag like `--url=env\(DATABASE_CONNECTION_STRING\)`).

`kysely-codegen` shouldn't crash if `.env` file doesn't exist.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/214">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/214/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/214/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment] 2024-10-26 13:37
Closing as duplicate of #212. Should be fixed in the beginning of the next week!

**Closed by RobinBlomberg** 2024-10-26 13:37 UTC

**Comment by thiagomini** [comment] 2024-12-04 18:36
Has this been fixed?
